apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: prod
  labels:
    env: prod
spec:
  selector:
    app: my-app
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
