apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort             # Add this line
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080       # Optional: fixed node port (30000-32767 range)
